name: Ilus APK Test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test Ilus file
        run: |
          echo "Ilus file received:"
          ls -la
          cat math.ilus

      - name: Upload Ilus file
        uses: actions/upload-artifact@v4
        with:
          name: ilus-test
          path: math.ilus
